- .gitignore
- AspNetCore.SassCompiler.Tasks/CompileSass.cs
- AspNetCore.SassCompiler.sln
- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
- AspNetCore.SassCompiler/build/AspNetCore.SassCompiler.props
- Samples/AspNetCore.SassCompiler.BlazorWasmSample/AspNetCore.SassCompiler.BlazorWasmSample.csproj
- Samples/AspNetCore.SassCompiler.BlazorWasmSample/Pages/Index.razor
- Samples/AspNetCore.SassCompiler.RazorClassLibrary/AspNetCore.SassCompiler.RazorClassLibrary.csproj
- Samples/AspNetCore.SassCompiler.RazorClassLibrary/Component1.razor
- Samples/AspNetCore.SassCompiler.RazorClassLibrary/Component1.razor.scss
- Samples/AspNetCore.SassCompiler.RazorClassLibrary/_Imports.razor
- Samples/AspNetCore.SassCompiler.RazorClassLibrary/sasscompiler.json
> Support using in razor classlib projects

- AspNetCore.SassCompiler.Tasks/CompileSass.cs
- AspNetCore.SassCompiler.Tasks/SimpleJson.cs
- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
- AspNetCore.SassCompiler/build/AspNetCore.SassCompiler.props
- README.md
> Fix MSBuild task reading json file with comments

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.62.1

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.63.4

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.63.6

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.64.1

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.68.0

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.69.2

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.69.3

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.71.1

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.75.0

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.77.1

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.77.4

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.79.3

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.79.5

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.80.1

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.80.4

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.80.5

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.80.6

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
- AspNetCore.SassCompiler/runtimes/linux-arm64/src/LICENSE
- AspNetCore.SassCompiler/runtimes/linux-x64/src/LICENSE
- AspNetCore.SassCompiler/runtimes/osx-arm64/src/LICENSE
- AspNetCore.SassCompiler/runtimes/osx-x64/src/LICENSE
- AspNetCore.SassCompiler/runtimes/win-x64/src/LICENSE
> Update dart-sass to 1.81.1

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.83.0

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.83.1

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
- AspNetCore.SassCompiler/runtimes/linux-arm64/src/LICENSE
- AspNetCore.SassCompiler/runtimes/linux-x64/src/LICENSE
- AspNetCore.SassCompiler/runtimes/osx-arm64/src/LICENSE
- AspNetCore.SassCompiler/runtimes/osx-x64/src/LICENSE
- AspNetCore.SassCompiler/runtimes/win-x64/src/LICENSE
> Update dart-sass to 1.83.4

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.85.1

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
- AspNetCore.SassCompiler/runtimes/linux-arm64/src/LICENSE
- AspNetCore.SassCompiler/runtimes/linux-x64/src/LICENSE
- AspNetCore.SassCompiler/runtimes/osx-arm64/src/LICENSE
- AspNetCore.SassCompiler/runtimes/osx-x64/src/LICENSE
- AspNetCore.SassCompiler/runtimes/win-x64/src/LICENSE
> Update dart-sass to 1.86.0

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.86.2

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
- AspNetCore.SassCompiler/runtimes/linux-arm64/src/LICENSE
- AspNetCore.SassCompiler/runtimes/linux-x64/src/LICENSE
- AspNetCore.SassCompiler/runtimes/osx-arm64/src/LICENSE
- AspNetCore.SassCompiler/runtimes/osx-x64/src/LICENSE
- AspNetCore.SassCompiler/runtimes/win-x64/src/LICENSE
> Update dart-sass to 1.87.0

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.88.0

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.89.0

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.91.0

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.93.0

- AspNetCore.SassCompiler/AspNetCore.SassCompiler.csproj
> Update dart-sass to 1.93.2
